server:
  port: 8081

spring:
  cloud:
    sentinel:
      enabled: true
      # 推荐开启传输层，便于在 dashboard 中查看资源和实时监控
      transport:
        dashboard: localhost:8090
        port: 8719
      eager: false

  application:
    name: chengwei
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chengwei?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    # password: 123321
    timeout: 5s
    database: 2
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON 处理时忽略空字段

mybatis-plus:
  type-aliases-package: com.chengwei.entity # 别名扫描包

logging:
  level:
    com.chengwei: debug

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

aliyun:
  oss:
    bucket-name: java-yjr
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing
