server:
  port: 8081
spring:
  cloud:
    sentinel:
      enabled: true
        # 鎺ㄨ崘锛氬紑鍚紶杈撳眰锛坉ashboard 鍙璧勬簮銆佸疄鏃剁洃鎺э級
      transport:
        dashboard: localhost:8090
        port: 8719
      eager: false

  application:
    name: chengwei
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    #password: 123321
    timeout: 5s
    database: 2
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON澶勭悊鏃跺拷鐣ラ潪绌哄瓧娈?
mybatis-plus:
  type-aliases-package: com.chengwei.entity # 鍒悕鎵弿鍖?
logging:
  level:
    com.chengwei: debug

aliyun:
  oss:
    bucket-name: java-yjr
    endpoint: https://oss-cn-beijing.aliyuncs.com
    region: cn-beijing

